/**
 * GF — AlarmesPage
 */
const { useState, useEffect } = React;
const { Bell, AlertTriangle, AlertOctagon, Settings, Plus, RefreshCw, X, MapPin, Truck, Clock, CheckCircle, ChevronDown, Edit3, Trash2, Save } = lucide;
const AlarmesPage = () => {
    const { alerts, handleDismissAlert, refreshAlerts } = GF.useFleet();
    const [activeTab, setActiveTab] = useState('alerts');
    const [rules, setRules] = useState([]);
    const [rulesLoading, setRulesLoading] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingRule, setEditingRule] = useState(null);
    const [expandedAlert, setExpandedAlert] = useState(null);
    const [newRule, setNewRule] = useState({ name: '', conditionType: 'parado_mais_que', threshold: '2', severity: 'warning' });
    const { addToast } = GF.useToast();
    useEffect(() => { (async () => { const res = await GF.api.getRules(); if (res.success && Array.isArray(res.rules)) setRules(res.rules); setRulesLoading(false); })(); }, []);
    const reloadRules = async () => { const res = await GF.api.getRules(); if (res.success && Array.isArray(res.rules)) setRules(res.rules); };
    const handleSaveRule = async () => { const rp = { name: newRule.name || 'Nova Regra', condition: newRule.conditionType, timeLimit: parseFloat(newRule.threshold) || 2, severity: newRule.severity || 'warning' }; if (editingRule) rp.ruleId = editingRule.id; const res = await GF.api.saveRule(rp); if (res.success) { await reloadRules(); addToast(editingRule ? 'Regra atualizada!' : 'Regra criada!', 'success'); } else { addToast('Erro ao salvar regra.', 'critical'); } closeModal(); };
    const handleDeleteRule = async (ruleId) => { if (!confirm('Deseja excluir esta regra?')) return; const res = await GF.api.deleteRule(ruleId); if (res.success) { await reloadRules(); addToast('Regra excluída.', 'info'); } else addToast('Erro ao excluir.', 'critical'); };
    const handleToggleRule = async (ruleId, currentActive) => { const res = await GF.api.toggleRule(ruleId, !currentActive); if (res.success) { await reloadRules(); addToast(currentActive ? 'Regra desativada.' : 'Regra ativada!', 'info'); } else addToast('Erro ao alterar.', 'critical'); };
    const openEditModal = (rule) => { setEditingRule(rule); setNewRule({ name: rule.name || '', conditionType: rule.condition || 'parado_mais_que', threshold: String(rule.timeLimit || 2), severity: rule.severity || 'warning' }); setIsModalOpen(true); };
    const openCreateModal = () => { setEditingRule(null); setNewRule({ name: '', conditionType: 'parado_mais_que', threshold: '2', severity: 'warning' }); setIsModalOpen(true); };
    const closeModal = () => { setIsModalOpen(false); setEditingRule(null); setNewRule({ name: '', conditionType: 'parado_mais_que', threshold: '2', severity: 'warning' }); };
    const sevColors = { alta: { bg: 'bg-red-50', border: 'border-red-200', text: 'text-red-700', badge: 'bg-red-100 text-red-700', dot: 'bg-red-500' }, warning: { bg: 'bg-amber-50', border: 'border-amber-200', text: 'text-amber-700', badge: 'bg-amber-100 text-amber-700', dot: 'bg-amber-500' }, info: { bg: 'bg-blue-50', border: 'border-blue-200', text: 'text-blue-700', badge: 'bg-blue-100 text-blue-700', dot: 'bg-blue-500' }, critical: { bg: 'bg-red-50', border: 'border-red-200', text: 'text-red-700', badge: 'bg-red-100 text-red-700', dot: 'bg-red-500' } };
    const condLabels = { parado_mais_que: 'Parado mais que', sem_apropriacao_mais_que: 'Sem apropriação mais que', manutencao_mais_que: 'Em manutenção mais que', desligado_mais_que: 'Motor desligado mais que' };
    return (
        <div className="p-4 md:p-8 h-full overflow-y-auto custom-scrollbar bg-slate-50 animate-fade-in">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 mb-6">
                <div className="flex items-center gap-3 md:gap-4"><div className="bg-red-600 p-2.5 md:p-3 rounded-xl text-white shadow-lg shadow-red-500/20 shrink-0"><Bell size={22} /></div><div className="min-w-0"><h1 className="text-lg md:text-2xl font-bold text-slate-800 truncate">Gerenciamento de Alarmes</h1><p className="text-slate-500 text-xs md:text-sm hidden sm:block">Alertas ativos e regras de monitoramento</p></div></div>
                <div className="flex items-center gap-2 md:gap-3 w-full sm:w-auto"><button onClick={refreshAlerts} className="flex-1 sm:flex-none bg-slate-100 text-slate-600 px-3 md:px-4 py-2 md:py-2.5 rounded-xl text-xs md:text-sm font-bold flex items-center justify-center gap-2 hover:bg-slate-200 transition-all"><RefreshCw size={14} /> Atualizar</button><button onClick={openCreateModal} className="flex-1 sm:flex-none bg-blue-600 text-white px-3 md:px-5 py-2 md:py-2.5 rounded-xl text-xs md:text-sm font-bold flex items-center justify-center gap-2 hover:bg-blue-500 transition-all shadow-lg shadow-blue-500/20 active:scale-95"><Plus size={16} /> Nova Regra</button></div>
            </div>
            <div className="flex gap-1 mb-6 bg-slate-100 p-1 rounded-xl w-fit">
                <button onClick={() => setActiveTab('alerts')} className={`px-5 py-2 rounded-lg text-sm font-bold transition-all flex items-center gap-2 ${activeTab === 'alerts' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}><AlertTriangle size={16} /> Alertas Ativos {alerts.length > 0 && <span className="bg-red-500 text-white text-[10px] font-bold px-2 py-0.5 rounded-full">{alerts.length}</span>}</button>
                <button onClick={() => setActiveTab('rules')} className={`px-5 py-2 rounded-lg text-sm font-bold transition-all flex items-center gap-2 ${activeTab === 'rules' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}><Settings size={16} /> Regras {rules.length > 0 && <span className="bg-blue-500 text-white text-[10px] font-bold px-2 py-0.5 rounded-full">{rules.length}</span>}</button>
            </div>
            {activeTab === 'alerts' && (<div className="space-y-4">{alerts.length === 0 ? (<div className="text-center py-20 bg-white rounded-2xl border-2 border-dashed border-slate-200"><CheckCircle size={48} className="mx-auto text-emerald-400 mb-4" /><p className="text-slate-500 font-bold text-lg">Nenhum alerta ativo</p><p className="text-slate-400 text-sm mt-1">Todos os sistemas estão operando normalmente.</p></div>) : alerts.map(alert => {
                const sev = sevColors[alert.severity] || sevColors.warning; const isExp = expandedAlert === alert.id;
                return (<div key={alert.id} className={`${sev.bg} border ${sev.border} rounded-2xl transition-all animate-fade-in overflow-hidden ${isExp ? 'ring-2 ring-offset-1 ring-blue-300' : ''}`}>
                    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between p-5 cursor-pointer" onClick={() => setExpandedAlert(isExp ? null : alert.id)}>
                        <div className="flex items-start gap-4 mb-3 sm:mb-0 flex-1"><div className={`p-3 rounded-xl ${sev.badge}`}><AlertTriangle size={22} /></div><div className="flex-1 min-w-0"><div className="flex items-center gap-2 mb-1 flex-wrap"><h4 className={`font-bold ${sev.text}`}>{alert.titulo || 'Alerta'}</h4><span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded-full ${sev.badge}`}>{alert.severity || 'warning'}</span></div><p className="text-sm text-slate-600 truncate">{alert.message}</p><div className="flex items-center gap-4 mt-2 text-xs text-slate-400"><span className="flex items-center gap-1"><MapPin size={12} /> {alert.vaga}</span><span className="flex items-center gap-1"><Truck size={12} /> {alert.equipamento}</span><span className="flex items-center gap-1"><Clock size={12} /> {GF.formatDateTime(alert.timestamp)}</span></div></div></div>
                        <div className="flex items-center gap-2 shrink-0"><ChevronDown size={16} className={`text-slate-400 transition-transform ${isExp ? 'rotate-180' : ''}`} /></div></div>
                    {isExp && (<div className="border-t border-slate-200/50 p-4 md:p-5 bg-white/50 animate-fade-in"><div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 mb-4"><div><span className="text-[10px] font-bold uppercase text-slate-400">Mensagem</span><p className="text-sm text-slate-700 mt-1">{alert.message}</p></div><div><span className="text-[10px] font-bold uppercase text-slate-400">Condição</span><p className="text-sm text-slate-700 mt-1 font-mono">{condLabels[alert.condition] || alert.condition || 'N/D'} {alert.timeLimit ? `${alert.timeLimit}h` : ''}</p></div><div><span className="text-[10px] font-bold uppercase text-slate-400">Severidade</span><p className="mt-1"><span className={`text-xs font-bold uppercase px-2 py-1 rounded-full ${sev.badge}`}>{alert.severity || 'warning'}</span></p></div></div>
                        <button onClick={(e) => { e.stopPropagation(); handleDismissAlert(alert.id); setExpandedAlert(null); }} className="bg-emerald-600 text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:bg-emerald-500 transition-all flex items-center gap-2 active:scale-95 shadow-lg shadow-emerald-500/20"><CheckCircle size={16} /> Marcar como Resolvido</button></div>)}</div>);
            })}
            </div>)}
            {activeTab === 'rules' && (<div className="space-y-4">{rulesLoading ? <div className="text-center py-12 text-slate-400">Carregando regras...</div> : rules.length === 0 ? (<div className="text-center py-20 bg-white rounded-2xl border-2 border-dashed border-slate-200"><Bell size={48} className="mx-auto text-slate-300 mb-4" /><p className="text-slate-500 font-bold text-lg">Nenhuma regra configurada</p><button onClick={openCreateModal} className="mt-6 bg-blue-600 text-white px-6 py-2.5 rounded-xl text-sm font-bold hover:bg-blue-500 inline-flex items-center gap-2 shadow-lg shadow-blue-500/20"><Plus size={18} /> Criar Primeira Regra</button></div>)
                : rules.map(rule => {
                    const rSev = sevColors[rule.severity] || sevColors.warning; const isIn = !rule.active;
                    return (<div key={rule.id} className={`group flex flex-col sm:flex-row items-start sm:items-center justify-between p-5 bg-white border rounded-2xl hover:shadow-md transition-all ${isIn ? 'border-slate-100 opacity-60' : 'border-slate-200 hover:border-blue-300'}`}>
                        <div className="flex items-center gap-5 mb-3 sm:mb-0 flex-1 min-w-0"><div className={`p-3 rounded-2xl shadow-sm shrink-0 ${isIn ? 'bg-slate-100 text-slate-400' : 'bg-blue-50 text-blue-500'}`}><Bell size={24} /></div><div className="min-w-0"><h4 className={`font-bold text-lg truncate ${isIn ? 'text-slate-400 line-through' : 'text-slate-800'}`}>{rule.name}</h4><p className="text-sm text-slate-500 mt-1 flex items-center gap-2 flex-wrap"><span className="bg-slate-100 px-2 py-0.5 rounded text-xs font-mono border border-slate-200">IF</span><span className="truncate">{condLabels[rule.condition] || rule.condition} {rule.timeLimit}h</span></p></div></div>
                        <div className="flex items-center gap-2 shrink-0"><span className={`text-[10px] font-bold uppercase px-2.5 py-1 rounded-full ${rSev.badge}`}>{rule.severity || 'N/D'}</span><button onClick={() => handleToggleRule(rule.id, rule.active)} className={`text-xs font-bold px-3 py-1.5 rounded-lg transition-all ${rule.active ? 'bg-emerald-100 text-emerald-700 hover:bg-emerald-200' : 'bg-slate-100 text-slate-400 hover:bg-slate-200'}`}>{rule.active ? 'Ativa' : 'Inativa'}</button><button onClick={() => openEditModal(rule)} className="p-2 rounded-lg bg-slate-50 text-slate-400 hover:bg-blue-50 hover:text-blue-600 transition-all"><Edit3 size={14} /></button><button onClick={() => handleDeleteRule(rule.id)} className="p-2 rounded-lg bg-slate-50 text-slate-400 hover:bg-red-50 hover:text-red-600 transition-all"><Trash2 size={14} /></button></div></div>);
                })}
            </div>)}
            {isModalOpen && (<div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fade-in"><div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6">
                <div className="flex justify-between items-center mb-6 border-b border-slate-100 pb-4"><h3 className="text-lg font-bold text-slate-800 flex items-center gap-2"><AlertOctagon className="text-blue-500" /> {editingRule ? 'Editar Regra' : 'Nova Regra de Alarme'}</h3><button onClick={closeModal} className="bg-slate-100 p-1 rounded-full hover:bg-slate-200"><X size={18} className="text-slate-500" /></button></div>
                <div className="space-y-4">
                    <div><label className="block text-xs font-bold uppercase text-slate-500 mb-1">Nome da Regra</label><input type="text" className="w-full border border-slate-300 rounded-lg p-3 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none" placeholder="Ex: Alerta de Ociosidade" value={newRule.name} onChange={e => setNewRule({ ...newRule, name: e.target.value })} /></div>
                    <div><label className="block text-xs font-bold uppercase text-slate-500 mb-1">Condição</label><select className="w-full border border-slate-300 rounded-lg p-3 text-sm bg-white focus:ring-2 focus:ring-blue-500 outline-none" value={newRule.conditionType} onChange={e => setNewRule({ ...newRule, conditionType: e.target.value })}><option value="parado_mais_que">Parado mais que X horas</option><option value="sem_apropriacao_mais_que">Sem apropriação mais que X horas</option><option value="manutencao_mais_que">Em manutenção mais que X horas</option><option value="desligado_mais_que">Motor desligado mais que X horas</option></select></div>
                    <div><label className="block text-xs font-bold uppercase text-slate-500 mb-1">Limite de Tempo (Horas)</label><input type="number" className="w-full border border-slate-300 rounded-lg p-3 text-sm focus:ring-2 focus:ring-blue-500 outline-none" placeholder="2" value={newRule.threshold} onChange={e => setNewRule({ ...newRule, threshold: e.target.value })} /></div>
                    <div><label className="block text-xs font-bold uppercase text-slate-500 mb-1">Severidade</label><div className="grid grid-cols-3 gap-2">{[{ k: 'info', l: 'Info', c: 'bg-blue-100 text-blue-700 border-blue-300' }, { k: 'warning', l: 'Warning', c: 'bg-amber-100 text-amber-700 border-amber-300' }, { k: 'alta', l: 'Alta', c: 'bg-red-100 text-red-700 border-red-300' }].map(s => (<button key={s.k} type="button" onClick={() => setNewRule({ ...newRule, severity: s.k })} className={`py-2.5 rounded-lg text-xs font-bold border-2 transition-all ${newRule.severity === s.k ? s.c + ' ring-2 ring-offset-1 ring-blue-400' : 'border-slate-200 text-slate-400 hover:border-slate-300'}`}>{s.l}</button>))}</div></div>
                    <div className="pt-4"><button onClick={handleSaveRule} className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-3.5 rounded-xl transition-colors flex items-center justify-center gap-2 shadow-lg"><Save size={18} /> {editingRule ? 'Atualizar Regra' : 'Salvar e Ativar'}</button></div>
                </div></div></div>)}
        </div>);
};
window.GF.AlarmesPage = AlarmesPage;
console.log('✅ [GF] AlarmesPage loaded');
